### ISSUE TITLE
fix runtime error for ./scan2html

### ISSUE THREAD

**Issue by afdesk** [afdesk/scan2html#48]
If we run `scan2html` itself we'll get a runtime error:
```
$ ./scan2html

panic: runtime error: slice bounds out of range [1:0]

goroutine 1 [running]:
main.makeTrivyJsonReport({0xc0000201c0?, 0x6?})
        /home/runner/work/scan2html/scan2html/main.go:86 +0x225
main.main()
        /home/runner/work/scan2html/scan2html/main.go:28 +0x205
```
so we should exit more gracefully here:

**Comment by malikovmm** [comment]
fixed in https://github.com/afdesk/scan2html/pull/51 
it displays help message when arguments is empty now
